#============================#
# server Setting
#============================#
server:
  port: 8002
  max-http-header-size: 10240

vaadin:
  compatibilityMode: false
  whitelisted-packages:logging: com.vaadin,org.vaadin,dev.hilla,com.example.application
  level:
    org:
      atmosphere: warn